language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm test
after_success:
  - git fetch --tags
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
