language: node_js
sudo: false
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - "8"
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run test:coverage
  - npm run build
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - git fetch --tags
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  local_dir: build
  bucket: crisboarna
  cache_control: "max-age=21600"
  on:
    branch: ["master"]
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"